FROM openjdk:8

ADD target/pingintelligence_usermanagement-0.0.1-SNAPSHOT.jar pingintelligence_usermanagement-0.0.1-SNAPSHOT.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "pingintelligence_usermanagement-0.0.1-SNAPSHOT.jar"]