# Generated by Django 3.1.7 on 2021-03-10 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('googleupload', '0008_auto_20210308_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='photo_id',
        ),
    ]
