apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: consumer-queue-1
  name: consumer-queue-1
spec:
  replicas: 4
  selector:
    matchLabels:
      io.kompose.service: consumer-queue-1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: consumer-queue-1
    spec:
      containers:
        - image: pingintelligence/consumer-queue-image-1:latest
          name: consumer-queue-1
          ports:
            - containerPort: 6500
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: consumer-queue-1
  name: consumer-queue-1
spec:
  ports:
    - name: "6500"
      port: 6500
      targetPort: 6500
  selector:
    io.kompose.service: consumer-queue-1
status:
  loadBalancer: {}
