version: '3'
services:
  ##### USER MANAGEMENT SERVICE ###### 
  mysql-user-mgmt:
    image: mysql:8.0.19
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root@123
      - MYSQL_DATABASE=UserManagement
    ports:
      - "3307:3306"
    volumes:
      - ./docker_volumes/user-mgmt/user_mgmt_db_data:/var/lib/mysql
  user-mgmt:
    image: pingintelligence/user-mgmt-image:latest #user-mgmt-image
    ports:
      - "8091:8091"
    depends_on:
      - mysql-user-mgmt
    restart: always


  ##### FRONT-END ###### 
  ui:
    image: pingintelligence/ui-image:latest
    ports:
      - "3000:3000"
    restart: always


  ##### API GATEWAY ###### 
  gateway:
    image: pingintelligence/gateway-image:latest
    ports:
      - "3001:3001"
    restart: always
    
  ##### IMAGE UPLOAD SERVICE ######       
  mysql-upload-mgmt:
    image: mysql:8.0.19
    restart: always
    command: --max_allowed_packet=67108864
    environment:
      - MYSQL_ROOT_PASSWORD=root@123
      - MYSQL_DATABASE=mainphotoupload
      - MYSQL_TCP_PORT=3308
    ports:
      - "3308:3308"
    volumes:
      - ./docker_volumes/upload-mgmt/upload_mgmt_db_data:/var/lib/mysql
    expose:
      - 3308      
  upload-mgmt:
    image: pingintelligence/upload-mgmt-image:latest
    ports:
      - "8092:8092"
    #build:
    depends_on:
      - mysql-upload-mgmt
      - kafka
    restart: always
    
  ##### KAFKA ######    
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
    - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.11-2.0.0
    depends_on:
    - zookeeper
    ports:
    - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "test1:1:1, test2:1:1"
      KAFKA_MESSAGE_MAX_BYTES: 30000000 
    volumes:
      - ./docker_volumes/kafka/kafka_data:/var/lib/mysql

  ##### Uploading to Google Drive ######  
  django-google:
    image: pingintelligence/googleupload-image:latest
    restart: always
    ports:
      - "9000:9000" 
    expose:
      - 9000
    depends_on:
      - kafka

  ############# kafka consumer queue 1 (for image add) ############
  consumer_queue:
    image: pingintelligence/consumer-queue-image:latest
    restart: always
    ports:
      - "7000:7000" 
    expose:
      - 7000
    depends_on:
      - kafka

  ############# kafka consumer queue 2 (for image delete) ############
  consumer_queue_1:
    image: pingintelligence/consumer-queue-image-1:latest
    restart: always
    ports:
      - "6500:6500" 
    expose:
      - 6500
    depends_on:
      - kafka
      
     ###### Metadatasearch #######
  metadata-search:
    image: pingintelligence/metadata-search-image:latest
    restart: always
    ports:
      - "8000:8000" 
    expose:
      - 8000