# Generated by Django 3.1.7 on 2021-03-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googleupload', '0004_auto_20210308_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='albumname',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='photo',
            name='link',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='photo_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='photodata',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
