# Generated by Django 2.1.5 on 2021-02-27 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchapi', '0003_auto_20210226_2004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metadata',
            old_name='annotation_tags',
            new_name='annotationtags',
        ),
    ]
