# Generated by Django 2.1.5 on 2021-02-27 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapi', '0004_auto_20210226_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='created_on',
            field=models.TextField(null=True),
        ),
    ]
