# Generated by Django 3.1.7 on 2021-03-08 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchapi', '0006_metadata_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metadata',
            old_name='photoname',
            new_name='title',
        ),
    ]
