# Generated by Django 2.1.5 on 2021-02-27 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='formats',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='height',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='mode',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='width',
            field=models.IntegerField(default='0'),
        ),
    ]
