# Generated by Django 3.1.7 on 2021-03-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapi', '0007_auto_20210308_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='image',
            field=models.TextField(null=True),
        ),
    ]
