# Generated by Django 3.1.7 on 2021-03-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapi', '0008_auto_20210310_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='albumname',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='image',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
