# Generated by Django 3.1.7 on 2021-03-09 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googleupload', '0007_photo_google_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(default='', max_length=300, unique=True),
        ),
    ]
