# Generated by Django 3.1.7 on 2021-02-24 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=64)),
                ('image', models.CharField(max_length=200)),
                ('image_id', models.CharField(max_length=200)),
                ('album', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='images.albums')),
            ],
        ),
    ]
