# Generated by Django 3.1.7 on 2021-02-24 16:59

from django.db import migrations, models
import images.models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='image_id_user',
            field=models.CharField(default='abc', max_length=100),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, upload_to=images.models.user_directory),
        ),
        migrations.AlterField(
            model_name='images',
            name='image_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
