# Generated by Django 3.1.7 on 2021-03-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googleupload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='albumname',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='photo',
            name='photodata',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
