# Generated by Django 3.1.7 on 2021-03-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googleupload', '0005_auto_20210308_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='annotationtags',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='photo',
            name='createdAt',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='photo',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='photo',
            name='photoname',
            field=models.CharField(default='', max_length=300),
        ),
    ]
