# Generated by Django 3.1.7 on 2021-03-09 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googleupload', '0006_auto_20210308_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='google_photo_id',
            field=models.TextField(null=True),
        ),
    ]
